#!/usr/bin/env php
<?php

use Palmyr\CodingStandards\Console\Application;



(function (): void
{
    $files = [
        __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'autoload.php',
        __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php',
    ];

    foreach ( $files as $file ) {
        if ( file_exists($file) && include $file ) {
            return;
        }
    }

    fwrite(STDERR, 'Install dependencies using Composer.'.PHP_EOL);
    exit(1);
})();

(new Application())->run();



